@userToken = <token>
Content-Type: application/json
Authorization: Bearer {{userToken}}


###
GET http://localhost:3000/api/departments/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

### 
POST http://localhost:3000/api/departments/
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "department" : {
        "name" : "Developpment"
    }
}


### 
PUT http://localhost:3000/api/departments/
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "department" : {
        "id" : "1",
        "info" : {
            "name" : "Developpment IT"
        }
    }
}

###
DELETE http://localhost:3000/api/departments/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

