@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoidXNlcjEiLCJlbWFpbCI6InVzZXIxQG1haWwuY29tIiwicm9sZSI6IkFETUlOIn0sImlhdCI6MTc4MTQzNzczMiwiZXhwIjoxNzgxNDQ0OTMyfQ.acAqpQBjIr1-RZereg5b41J5iwuhLYTzzu_tnhlqVJE

###
GET http://localhost:3000/api/departments
Content-Type: application/json
Authorization: Bearer {{userToken}}


###
GET http://localhost:3000/api/departments/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

### 
POST http://localhost:3000/api/departments/
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "department" : {
        "name" : "Networking"
    }
}


### 
PUT http://localhost:3000/api/departments/
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "department" : {
        "id" : "1",
        "info" : {
            "name" : "Developpment IT"
        }
    }
}

###
DELETE http://localhost:3000/api/departments/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

